{% if item.registry is defined %}
	FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
	FROM {{ item.image }}
{% endif %}

{% if item.env is defined %}
	{% for var, value in item.env.items() %}
		{% if value %}
			ENV {{ var }} {{ value }}
		{% endif %}
	{% endfor %}
{% endif %}

RUN apk update \
	&& apk add --no-cache bash ca-certificates curl openrc python3 sudo vim; \
	echo 'rc_provide="loopback net"' >> /etc/rc.conf;
