---
# tasks file for wordpress
- name: Wordpress | Install prerequisites packages
  apk:
    name: ["tar", "apache2" ]
    update_cache: yes
    state: present
  tags: package

- name: Wordpress | Install PHP packages
  apk:
    name: "{{ php_packages + php_extra_packages }}"
    update_cache: yes
    state: present
  tags: package

- name: Wordpress | Create directory in Apache document root for Wordpress
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0755
  tags: configure

- name: Wordpress | Ensure site-enabled/sites-available paths exist in Apache configuration directory
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0755
  with_items:
    - "{{ apache_site_available_dir }}"
    - "{{ apache_site_enabled_dir }}"
  tags: configure

- name: Wordpress | Configure httpd.conf for Apache
  template:
    src: httpd.conf.j2
    dest: "{{ apache_confdir }}/httpd.conf"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    mode: 0755
  notify: Reload Apache
  tags: configure

- name: Wordpress | Configure Apache virtualhost for Wordpress
  template:
    src: wordpress.conf.j2
    dest: "{{ apache_site_available_dir }}/wordpress.conf"
    owner: "{{ apache_user }}"
    group: '{{ apache_group }}'
    mode: 0755
  notify: Reload Apache
  tags: configure

- name: Wordpress | Create symlink in site-enabled for Wordpress
  file:
    src: "{{ apache_site_available_dir }}/wordpress.conf"
    dest: "{{ apache_site_enabled_dir }}/wordpress.conf"
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
    state: link
  notify: Reload Apache
  tags: configure

- name: Wordpress | Download and extract Wordpress archive
  unarchive:
    src: "https://wordpress.org/{{ wp_version }}.tar.gz"
    dest: "/var/www/{{ http_host }}"
    remote_src: yes
    creates: "/var/www/{{ http_host }}/wordpress"
  tags: configure

- name: Wordpress | Configure ownership and permissions on Apache document root
  file:
    path: "/var/www/{{ http_host }}"
    state: directory
    recurse: yes
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
  tags: configure

- name: Wordpress | Configure wp-config.php
  template:
    src: wp-config.php.j2
    dest: "/var/www/{{ http_host }}/wordpress/wp-config.php"
    mode: 0755
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"
  # Authentication unique keys and salts are randomly generated and break idempotency (disable idempotency here for tests)
  changed_when: "'molecule-idempotence-notest' not in ansible_skip_tags"
  tags: configure

- name: Wordpress | Start and enable Apache
  service: name=apache2 state=started enabled=yes
  tags: service
