---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
    requirements-file: collections.yml
driver:
  name: docker
platforms:
  - name: alpine
    image: alpine:3.13.5
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: /sbin/init
test_sequence:
  - lint
  - destroy
  - dependency
  - syntax
  - create
  - prepare
  - converge
  - idempotence
  - verify
  - destroy
provisioner:
  name: ansible
verifier:
  name: testinfra
