---
dependency:
  name: galaxy
  options:
    ignore-certs: True
    ignore-errors: True
    role-file: requirements.yml
    requirements-file: collections
driver:
  name: docker
platforms:
  - name: alpine
    image: alpine:3.13.5
    dockerfile: ../common/Dockerfile.j2
    privileged: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
    command: "/sbin/init"

provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: ansible
